BibliotecaWeb/Models/ErrorViewModel.cs
namespace BibliotecaWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BibliotecaWeb/Controllers/CategoriaController.cs
using CapaDatos;
using CapaModelo;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaWeb.Controllers
{
    public class CategoriaController : Controller
    {
        public IActionResult Crear()
        {
            return View();
        }

        [HttpGet]

        public JsonResult Obtener() {
            List<Categoria> lista = CD_Categoria.Instancia.ObtenerCategoria();
            return Json(new { data = lista }); 
        }

        public JsonResult Guardar(Categoria objeto) 
        {
            bool respuesta = false;
            if (objeto.CategoriaID == 0)
                respuesta = CD_Categoria.Instancia.RegistrarCategoria(objeto);
            else
                respuesta = CD_Categoria.Instancia.ModificarCategoria(objeto);
            return Json(new
            {
                resultado = respuesta
            });

        }

       
          [HttpGet]

          public JsonResult Eliminar(int id = 0)
          {
                bool respuesta = CD_Categoria.Instancia.EliminarCategoria(id);
                return Json(new { resultado = respuesta });
          }


    }
}

BibliotecaWeb/Controllers/HomeController.cs
using BibliotecaWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BibliotecaWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BibliotecaWeb/Views/Categoria/Crear.cshtml
@model CapaModelo.Categoria
@{
    ViewBag.Title = "Crear";
    Layout = "/Views/Shared/_Layout.cshtml";
}

<div class=" content-wrapper" style="padding : 10px">
    <div class="col-sm-12">
        <div class="card border-info">
            <div class="card-header bg-info text-white">
                Lista Categorias
            </div>
            <div class=" card-body ">
                <div class="row">
                    <div class="col-sm-4">
                  </diy>
                    </div>
                    <hr />
                    <div class="row mt-3">
                        <div class="col-sm-12">
                            <table id="tbdata" class="table table-striped table-bordered nowrap compact" style=" width:100%">
                                <thead>
                                    <tr>
                                        <th>CodigoID</th>
                                        <th>Nombre</th>
                                        <th>Descripcion</th>
                                       
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section Scripts{
        <partial name="_ValidationScriptsPartial" />
        <script src="~/js/Crudcategoria.js"></script>
    }

BibliotecaWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BibliotecaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BibliotecaWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BibliotecaWeb.styles.css" asp-append-version="true" />
    <Link rel="stylesheet" href="~/DataTables/DataTables-1.13.6/css/dataTables. bootstrap5. min.css" />
    <link rel="stylesheet" href="~/DataTables/Buttons-2.4.2/css/buttons . bootstrap5. min.css" />
    <link rel="stylesheet " href=" /css/sweetalert2. css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BibliotecaWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Crear">Categoria</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BibliotecaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/sweetalert2. all. js"></script>
    <script src="~/lib/jquery/dist/jquery.min. js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap. bundle . min.js"></script>
    <script Src="~/js/site. js" asp-append-version="true "></script>
    <script type="text/javascript" src="~/DataTables/JSZip-3.10. 1/jszip.min. js"></script>
    <script type="text/javascript" src="~/DataTables/pd fmake-0.1.36/pdfmake. min.js"></script>
    <script type="text/javascript" src="~/DataTables/pdfmake-0.2.7/vfs_fonts.js"></script>
    <script type="text/javascript" src="~/DataTables/DataTables-1. 13.6/js/jquery. dataTables . min. js"></script>
    <script type="text/javascript " src="/DataTables/DataTables-1.13.6/js/dataTables . bootstrap5. min.js"></script>
    <script type="text/javascript " src="/DataTables/Buttons-2 . 4.2/js/dataTables. buttons. min. js"></script>
    <script type="text/javascript" src="/DataTables/Buttons-2.4.2/js/buttons. bootstrap5. min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/buttons.colVis . min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/buttons .html5.min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/buttons .print. min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>